config/routes.rb
Toudoux::Application.routes.draw do
  resources :intervenants

  resources :operations

  resources :opegroups

  get "events/index"
  get "events/install_status"
  get "events/period/:period" => "events#index"
  get "events/newcal"

  get "test_it/index"

  get "welcome/account"
  get "welcome/indexmap"
  get "welcome/stat"
  get "welcome/graph_install"
  get "welcome/graph_migrate"
  get "welcome/pie_status"
  match "welcome/sample_ajax/:id" => "welcome#sample_ajax"

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}
  
  resources :entities

  resources :environments

  resources :instances do
  	  resources :events do
 	  	resources :intervenants, :controller => "event_interv_links"
  	  end
  end

  resources :servers do
  	  resources :events do
  	  	resources :intervenants, :controller => "event_interv_links" 
	  end
  end

  resources :branches do
  	  resources :events do
  	  	resources :intervenants, :controller => "event_interv_links"
  	  end
  end

  get "welcome/index"

  devise_for :users

  root :to => "welcome#index"

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :servers 
  has_many :instances
  belongs_to :entity
  has_many :events, :as => :eventable
end

app/controllers/branches_controller.rb
require 'iconv'
require 'csv'
class BranchesController < ApplicationController
  BOM = "\377\376" #Byte Order Mark
  before_filter :authenticate_user!
  # GET /branches
  # GET /branches.xml
  def index
  	@title = "toutes les agences"
    @branches = Branch.all
    respond_to do |format|
		format.html # index.html.erb
		format.xml  { render :xml => @branches }
		format.iphone { render :layout => false }
		format.csv do
			filename = I18n.l(Time.now, :format => :short) + "- branches.csv"	
	      	csv_string = CSV.generate do |csv|
		        # header row
		        csv << ["Id", "Name", "Description", "Entite"]
		
		        # data rows
		        @branches.each do |branch|
		          csv << [ branch.id,
	           			   branch.name,
	           			   branch.description,
	           			   branch.entity.description]
		        end
			end
		# csv_string = BOM + Iconv.conv("utf-16le", "utf-8", csv_string)
	    # send it to the browsah
	    send_data csv_string,
	                :type => 'text/csv; charset=utf-8; header=present',
	                :disposition => "attachment;",
	                :filename => filename
		end    
	end
  end

  # GET /branches/1
  # GET /branches/1.xml
  def show
    @branch = Branch.find(params[:id])
  	@title = @branch.description + " - " + @branch.name 
    @interventions = @branch.events.order("coalesce(cancelled,done,planned) ASC")

    respond_to do |format|
      format.html # show.html.erb
      format.iphone { render :layout => false } # show.iphone.erb
      format.xml  { render :xml => @branch }
    end
  end

  # GET /branches/new
  # GET /branches/new.xml
  def new
    @branch = Branch.new
    @entities = Entity.find(:all)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @branch }
    end
  end

  # GET /branches/1/edit
  def edit
    @branch = Branch.find(params[:id])
    @entities = Entity.find(:all)
  end

  # POST /branches
  # POST /branches.xml
  def create
    @branch = Branch.new(params[:branch])

    respond_to do |format|
      if @branch.save
        format.html { redirect_to(@branch, :notice => 'Branch was successfully created.') }
        format.xml  { render :xml => @branch, :status => :created, :location => @branch }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @branch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /branches/1
  # PUT /branches/1.xml
  def update
    @branch = Branch.find(params[:id])

    respond_to do |format|
      if @branch.update_attributes(params[:branch])
        format.html { redirect_to(@branch, :notice => 'Branch was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @branch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.xml
  def destroy
    @branch = Branch.find(params[:id])
    @branch.destroy

    respond_to do |format|
      format.html { redirect_to(branches_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "erreur") %> empêche cette agence d'être sauvegardée:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nom" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :entity_id, "Entité" %><br />
    <%= f.select :entity_id, @entities.collect {|s| [s.name, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :long, "Longitude" %><br />
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :lat, "Latitude" %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :refreshed %><br />
    <%= select(:branch, :refreshed, options_for_select([['non', 1], ['planifié', 2], ['réalisé', 3], ['a corriger', 4], ['erreur', 5]],@branch.refreshed)) %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Modification d'agence</h1>

<%= render 'form' %>

<%= link_to 'Voir', @branch %> |
<%= link_to 'Retour', branches_path %>

app/views/branches/index.html.erb
<h1>Agences</h1>
<%= link_to image_tag("csv.jpg", :border=>0), params.merge(:format => :csv), :action => :index %>
<table>
  <tr>
    <th>Nom</th>
    <th>Description</th>
    <th>Entité</th>
    <th>Note</th>
    <th></th>
    <th></th>
    
  </tr>

<% @branches.each do |branch| %>
  <tr>
    <td><%= link_to branch.name, branch %></td>
    <td><%= branch.description %></td>
    <td><%= branch.entity.name %></td>
    <td><%= branch.note %></td>
    <td><%= link_to 'Modifie', edit_branch_path(branch) %></td>
    <td><%= link_to 'Détruit', branch, :confirm => 'Êtes-vous sûr?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to "Création d'agence", new_branch_path %>

app/views/branches/index.iphone.erb
<ul title="Agences" selected="true">
<% for branch in @branches -%>
<li><%= link_to h(branch.name), branch_path(branch) %></li>
<% end -%>
<li class="group">Actions</li>
<li>
<%= link_to 'Add branch', new_branch_path %>
</li>
</ul>

app/views/branches/new.html.erb
<h1>Nouvelle agence</h1>

<%= render 'form' %>

<%= link_to 'Retour', branches_path %>

app/views/branches/new.iphone.erb
<%= form_for(@branch, :url => branch_path,
			:html => {:class => 'panel',
			:selected => 'true',
			:title => 'Ajoute agence'}) do |f| %>
  <div class="row">
    <%= f.label :name, "Nom" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="row">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="row">
    <%= f.label :entity_id, "Entité" %><br />
    <%= f.select :entity_id, @entities.collect {|s| [s.name, s.id]} %>
  </div>
  <div class="row">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="row">
    <%= f.label :refreshed %><br />
    <%= select(:branch, :refreshed, options_for_select([['non', 1], ['planifié', 2], ['réalisé', 3], ['a corriger', 4], ['erreur', 5]],@branch.refreshed)) %> 
  </div>
  <div class="whiteButton">
    <%= f.submit %>
  </div>
<% end %>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @branch.name %>
</p>

<p>
  <b>Description:</b>
  <%= @branch.description %>
</p>

<p>
  <b>GPS:</b>
  <%= @branch.long %>,<%= @branch.lat %>
</p>

<p>
  <b>Entité:</b>
  <%= link_to @branch.entity.name, @branch.entity %>
</p>

<p>
  <b>Note:</b>
  <%= @branch.note %>
</p>

<p>
  <b>Refresh Serveur:</b>
<% case %>
<%   when @branch.refreshed == 1 then %>
  Non traité
<%   when @branch.refreshed == 2 then %>
  Planifié
<%   when @branch.refreshed == 3 then %>
  Réalisé
<%   when @branch.refreshed == 4 then %>
  A corriger
<%   when @branch.refreshed == 5 then %>
  <b>Erreur</b>
<% end %>  
</p>

<table>
<thead>
	<tr>
	  <th class="span 5">Nom</th>
	  <th class="span 7">Desciption</th>
	  <th class="span 12">Note</th>
	</tr>
</thead>
<tbody>
<% @branch.servers.each do |server| %>
  <tr>
    <td><%= link_to server.name, server%></td>
    <td><%= server.description %></td>
    <td><%= server.note %></td>
  </tr>
<% end %>
</tbody>
</table>

<%= render :partial => "shared/events_by_branch", :locals => { :events => @interventions } %>

<%= link_to "Ajout d'opération", new_branch_event_path(@branch) %>
<%= link_to 'Modifier', edit_branch_path(@branch) %> |
<%= link_to 'Retour', branches_path %>

app/views/branches/show.iphone.erb
<div class="panel" title="Test" selected="true">
    <h2><%= @branch.description %></h2>
    <p><%= @branch.note %></p>
    <p><%= @branch.entity.name %></p>
</div>