config/routes.rb
Toudoux::Application.routes.draw do
  resources :intervenants

  resources :operations

  resources :opegroups

  get "events/index"
  get "events/install_status"
  get "events/period/:period" => "events#index"
  get "events/newcal"

  get "test_it/index"

  get "welcome/account"
  get "welcome/indexmap"
  get "welcome/stat"
  get "welcome/graph_install"
  get "welcome/graph_migrate"
  get "welcome/pie_status"
  match "welcome/sample_ajax/:id" => "welcome#sample_ajax"

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}
  
  resources :entities

  resources :environments

  resources :instances do
  	  resources :events do
 	  	resources :intervenants, :controller => "event_interv_links"
  	  end
  end

  resources :servers do
  	  resources :events do
  	  	resources :intervenants, :controller => "event_interv_links" 
	  end
  end

  resources :branches do
  	  resources :events do
  	  	resources :intervenants, :controller => "event_interv_links"
  	  end
  end

  get "welcome/index"

  devise_for :users

  root :to => "welcome#index"

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  belongs_to :environment
  belongs_to :branch
  belongs_to :server
  has_many :events, :as => :eventable
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_filter :authenticate_user!

  # GET /instances
  # GET /instances.xml
  def index
    @instances = Instance.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @instances }
    end
  end

  # GET /instances/1
  # GET /instances/1.xml
  def show
    @instance = Instance.find(params[:id])
    @interventions = @instance.events.order("coalesce(cancelled,done,planned) ASC")

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @instance }
    end
  end

  # GET /instances/new
  # GET /instances/new.xml
  def new
    @instance = Instance.new
    @servers = Server.find(:all)
    @branches = Branch.find(:all)
    @environments = Environment.find(:all)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @instance }
    end
  end

  # GET /instances/1/edit
  def edit
    @instance = Instance.find(params[:id])
    @servers = Server.find(:all)
    @branches = Branch.find(:all)
    @environments = Environment.find(:all)
  end

  # POST /instances
  # POST /instances.xml
  def create
    @instance = Instance.new(params[:instance])

    respond_to do |format|
      if @instance.save
        format.html { redirect_to(@instance, :notice => 'Instance was successfully created.') }
        format.xml  { render :xml => @instance, :status => :created, :location => @instance }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @instance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /instances/1
  # PUT /instances/1.xml
  def update
    @instance = Instance.find(params[:id])

    respond_to do |format|
      if @instance.update_attributes(params[:instance])
        format.html { redirect_to(@instance, :notice => 'Instance was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @instance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /instances/1
  # DELETE /instances/1.xml
  def destroy
    @instance = Instance.find(params[:id])
    @instance.destroy

    respond_to do |format|
      format.html { redirect_to(instances_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_form.html.erb
<%= form_for(@instance) do |f| %>
  <% if @instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instance.errors.count, "erreur") %> empêche cette instance d'être sauvegardée:</h2>

      <ul>
      <% @instance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sid, "SID base de données" %><br />
    <%= f.text_field :sid %>
  </div>
  <div class="field">
    <%= f.label :db, "Nom de base de données" %><br />
    <%= f.text_field :db %>
  </div>
  <div class="field">
    <%= f.label :server_id, "Serveur" %><br />
    <%= f.select :server_id, @servers.collect {|s| [s.name, s.id]}  %>
  </div>
  <div class="field">
    <%= f.label :branch_id, "Agence" %><br />
    <%= f.select :branch_id, @branches.collect {|s| [s.name, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :environment_id, "Environnement" %><br />
    <%= f.select :environment_id, @environments.collect {|s| [s.name, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instances/edit.html.erb
<h1>Modification d'instance</h1>

<%= render 'form' %>

<%= link_to 'Voir', @instance %> |
<%= link_to 'Retour', instances_path %>

app/views/instances/index.html.erb
<h1>Instances</h1>

<table>
  <tr>
    <th>SID</th>
    <th>Nom BDD</th>
    <th>Serveur</th>
    <th>Agence</th>
    <th>Environnement</th>
    <th>Description</th>
    <th>Note</th>
    <th></th>
    <th></th>
  </tr>

<% @instances.each do |instance| %>
  <tr>
    <td><%= link_to instance.sid, instance %></td>
    <td><%= instance.db %></td>
    <td><%= link_to instance.server.name, instance.server %></td>
    <td><%= link_to instance.branch.name, instance.branch %></td>
    <td><%= instance.environment.name %></td>
    <td><%= instance.description %></td>
    <td><%= instance.note %></td>
    <td><%= link_to 'Modifie', edit_instance_path(instance) %></td>
    <td><%= link_to 'Détruit', instance, :confirm => 'Êtes-vous sûr?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nouvelle instance', new_instance_path %>

app/views/instances/new.html.erb
<h1>Nouvelle instance</h1>

<%= render 'form' %>

<%= link_to 'Retour', instances_path %>

app/views/instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>SID:</b>
  <%= @instance.sid %>
</p>

<p>
  <b>Nom BDD:</b>
  <%= @instance.db %>
</p>

<p>
  <b>Serveur:</b>
  <%= link_to @instance.server.name, @instance.server %>
</p>

<p>
  <b>Agence:</b>
  <%= link_to @instance.branch.entity.name, @instance.branch.entity %>&nbsp;<%= link_to @instance.branch.name, @instance.branch %>
</p>

<p>
  <b>Environnement:</b>
  <%= @instance.environment.name %>
</p>

<p>
  <b>Description:</b>
  <%= @instance.description %>
</p>

<p>
  <b>Note:</b>
  <%= @instance.note %>
</p>

<%= render :partial => "shared/events", :locals => { :events => @interventions } %>

<%= link_to "Ajout d'opération", new_instance_event_path(@instance) %>
<%= link_to 'Modifier', edit_instance_path(@instance) %> |
<%= link_to 'Retour', instances_path %>