config/routes.rb
Toudoux::Application.routes.draw do
  resources :intervenants

  resources :operations

  resources :opegroups

  get "events/index"
  get "events/install_status"
  get "events/period/:period" => "events#index"
  get "events/newcal"

  get "test_it/index"

  get "welcome/account"
  get "welcome/indexmap"
  get "welcome/stat"
  get "welcome/graph_install"
  get "welcome/graph_migrate"
  get "welcome/pie_status"
  match "welcome/sample_ajax/:id" => "welcome#sample_ajax"

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}
  
  resources :entities

  resources :environments

  resources :instances do
  	  resources :events do
 	  	resources :intervenants, :controller => "event_interv_links"
  	  end
  end

  resources :servers do
  	  resources :events do
  	  	resources :intervenants, :controller => "event_interv_links" 
	  end
  end

  resources :branches do
  	  resources :events do
  	  	resources :intervenants, :controller => "event_interv_links"
  	  end
  end

  get "welcome/index"

  devise_for :users

  root :to => "welcome#index"

end

app/controllers/welcome_controller.rb
require 'open_flash_chart'
class WelcomeController < ApplicationController
  helper :application
  include GmailsHelper
    	
  def index
    if user_signed_in?
        setlimits
        getevents # if iphone_user_agent?
    end
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @ope }
      format.iphone 
    end
  end
  
  def indexmap
    if user_signed_in?
		  @data = Branch.all
   	  @map = set_gmail(@data)
    end
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @data }
      format.iphone {render :action => :index}
    end
  end
  
  def stat
    @title = "Statistiques"
    respond_to do |format|
      format.html {
        if user_signed_in?
          @graph1 = open_flash_chart_object( 960, 400, '/welcome/graph_install' )
          @graph2 = open_flash_chart_object( 960, 400, '/welcome/graph_migrate' )
          @graph3 = open_flash_chart_object( 470, 400, '/welcome/pie_status' )
        end  
      } 
      format.xml  { render :xml => @data }
      format.iphone {render :action => :index}
    end
  end
  
  def sample_ajax
  	@branch = Branch.find(params[:id])
    respond_to do |format|
      format.html { render :layout => false}
      format.xml  { render :xml => @branch }
    end
  end	
   
  def account
    
  end

  def graph_install
    rendergraph(4, "d'installations")
  end

  def graph_migrate
    rendergraph(3, "de migrations")
  end
  
  def pie_status
    renderpie
  end

private

  def getevents
  	myquery = <<-SQL
  	select b1.*,
	CASE WHEN cancelled is null THEN
	  CASE WHEN done is null THEN
	    'planned'
	  else
	  	'done'   
	  END	
	ELSE 'cancelled'
    END as status  	
  from  (
SELECT 
  branches.id as branch_id, 
  branches."name" as branch_name, 
  branches.description as branch_description, 
  branches.id as target_id, 
  branches."name" as target_name, 
  branches.description as target_description, 
  entities.id as entity_id, 
  entities."name" as entity_name, 
  entities.description as entity_description, 
  operations.id as operation_id, 
  operations."name" as operation_name, 
  operations.description as operation_description, 
  opegroups.id as opegroup_id, 
  opegroups."name" as opegroup_name, 
  opegroups.description as opegroup_description, 
  events.id as id, 
  events.description as description, 
  events.planned as planned, 
  events.done as done, 
  events.cancelled as cancelled,
  coalesce(events.cancelled,events.done,events.planned) as date_used, 
  events.eventable_type
FROM 
  brinks.events, 
  brinks.branches, 
  brinks.operations, 
  brinks.opegroups, 
  brinks.entities
WHERE 
  events.eventable_id = branches.id AND
  events.operation_id = operations.id AND
  branches.entity_id = entities.id AND
  operations.opegroup_id = opegroups.id AND
  events.eventable_type = 'Branch'
union
SELECT 
  branches.id, 
  branches."name", 
  branches.description, 
  servers.id,
  servers.name,
  servers.description,
  entities.id, 
  entities."name", 
  entities.description, 
  operations.id, 
  operations."name", 
  operations.description, 
  opegroups.id, 
  opegroups."name", 
  opegroups.description, 
  events.id, 
  events.description, 
  events.planned, 
  events.done, 
  events.cancelled, 
  coalesce(events.cancelled,events.done,events.planned) as date_used, 
  events.eventable_type
FROM 
  brinks.events, 
  brinks.servers, 
  brinks.branches, 
  brinks.operations, 
  brinks.opegroups, 
  brinks.entities
WHERE 
  events.eventable_id = servers.id AND
  events.operation_id = operations.id AND
  branches.id = servers.branch_id AND
  branches.entity_id = entities.id AND
  operations.opegroup_id = opegroups.id AND
  events.eventable_type = 'Server'
union
SELECT 
  branches.id, 
  branches."name", 
  branches.description, 
  instances.id,
  instances.sid,
  instances.description,
  entities.id, 
  entities."name", 
  entities.description, 
  operations.id, 
  operations."name", 
  operations.description, 
  opegroups.id, 
  opegroups."name", 
  opegroups.description, 
  events.id, 
  events.description, 
  events.planned, 
  events.done, 
  events.cancelled, 
  coalesce(events.cancelled,events.done,events.planned) as date_used, 
  events.eventable_type
FROM 
  brinks.events, 
  brinks.instances, 
  brinks.branches, 
  brinks.operations, 
  brinks.opegroups, 
  brinks.entities
WHERE 
  events.eventable_id = instances.id AND
  events.operation_id = operations.id AND
  branches.id = instances.branch_id AND
  branches.entity_id = entities.id AND
  operations.opegroup_id = opegroups.id AND
  events.eventable_type = 'Instance'
) b1  
where opegroup_name = 'SRV_REFRESH' and 
  ((planned between '#{@startdate}' and '#{@enddate}') or 
   (done between '#{@startdate}' and '#{@enddate}') or 
   (cancelled between '#{@startdate}' and '#{@enddate}')
  ) 
  order by coalesce(cancelled,done,planned) ASC, branch_name, operation_name 
  SQL
  	
  	@ope = Event.connection.select_all(myquery)
  end

  def getstat
    myquery = <<-SQL
      select mydate, 
      e.operation_id,
      sum(case 
        when e.planned<=mydate then 1 
        else 0
      end) as planned,  
      sum(case 
        when e.done is not null and e.done <= mydate then 1
        else 0
      end) as done,
      sum(case 
        when e.cancelled is not null and e.cancelled <= mydate then 1
        else 0
      end) as cancelled
      from (
        select distinct e.planned as mydate from brinks.events e where e.operation_id in (3,4)
        union 
        select distinct e.done as mydate  from brinks.events e where e.operation_id in (3,4)
      ) as b1
      inner join brinks.events e on (e.operation_id in (3,4))
      where mydate is not null
      group by mydate, e.operation_id
      order by mydate, e.operation_id
  SQL

    @stat = Event.connection.select_all(myquery)
      
  end  

  def getpie_now
    myquery = <<-SQL
      select 
        count(b.id) as value,        
        case 
          when emig.done is not null then
            'Installe & Migre'
          when emig.cancelled is not null then
            'Migration abandonnee'
          when einst.done is not null then 
            'Installe'
          when einst.cancelled is not null then
            'Installation abandonnee'
          else
            'Planifie'
         end as libelle
      from brinks.branches b
      inner join brinks.servers s on (s.branch_id=b.id)
      left outer join brinks.events einst on (einst.eventable_type='Branch' and einst.eventable_id=b.id and einst.operation_id=4)
      left outer join brinks.events emig on (emig.eventable_type='Branch' and emig.eventable_id=b.id and emig.operation_id=3)
      where s.description not like 'IBM Model%' and
      s.alias <> ''
      group by 2
      order by 2    
    SQL

    @stat = Event.connection.select_all(myquery)
          
  end

  def rendergraph(typestat, lib)
    caption_x = []
    dataplan = []
    datadone = []
    datacancel = []
    lastyear = nil
    lastweek = nil
    lastdate = nil
    
    getstat
    
    @stat.each do |s|
      if (s["operation_id"].to_i == typestat) && (s["mydate"].to_date > "2011-01-01".to_date)
        year = s["mydate"].to_date.cwyear
        week = s["mydate"].to_date.cweek
        while (lastyear.nil?) || (lastyear<year) || ((lastyear==year) && (lastweek<week)) do
          if lastyear.nil?
            lastyear = year
            lastweek = week
            lastdate = s["mydate"].to_date
            if lastdate.wday==0
              lastdate = lastdate - 6
            else  
              lastdate = lastdate - lastdate.wday + 1
            end 
            caption_x << lastdate.day.to_s + "-" + lastdate.month.to_s + "-" + lastdate.year.to_s
            dataplan << 0
            datadone << 0
            datacancel << 0
          elsif (lastyear<year) || ((lastyear==year) && (lastweek<week)) 
            lastdate = lastdate + 7
            lastyear = lastdate.cwyear
            lastweek = lastdate.cweek
            caption_x << lastdate.day.to_s + "-" + lastdate.month.to_s + "-" + lastdate.year.to_s
            dataplan << dataplan.last
            datadone << datadone.last
            datacancel << datacancel.last
          end  
        end
        if (lastyear==year) && (lastweek == week) 
            dataplan[dataplan.length-1] = s["planned"].to_i
            datadone[datadone.length-1] = s["done"].to_i
            datacancel[datacancel.length-1] = s["cancelled"].to_i
        end 
      end       
    end


    # based on this example - http://teethgrinder.co.uk/open-flash-chart-2/data-lines-2.php
    title = Title.new("Etats des #{lib.split(" ").last.split("'").last}")

    line_dot = Line.new
    line_dot.text = "Planifie"
    line_dot.width = 4
    line_dot.colour = '#DFC329'
    line_dot.dot_size = 5
    line_dot.values = dataplan

    line_hollow = Bar.new
    line_hollow.text = "Realise"
    line_hollow.width = 1
    line_hollow.colour = '#6363AC'
    line_hollow.dot_size = 5
    line_hollow.values = datadone

    line = Bar.new
    line.text = "Abandonne"
    line.width = 1
    line.colour = '#FF3333'
    line.dot_size = 5
    line.values = datacancel
     
     
    tmp = []
    
    x_labels = XAxisLabels.new
    x_labels.visible_steps = 2
    x_labels.rotate = -90

    caption_x.each do |text|
      tmp << XAxisLabel.new(text, '#0000ff', 12, '')
    end

    x_labels.labels = tmp

    x = XAxis.new
    x.set_labels(x_labels)

    y = YAxis.new
    y.set_range(0,70,5)

    x_legend = XLegend.new("Semaines")
    x_legend.set_style('{font-size: 20px; color: #778877}')

    y_legend = YLegend.new("Nombre #{lib}")
    y_legend.set_style('{font-size: 20px; color: #770077}')

    chart = OpenFlashChart.new
    chart.set_title(title)
    chart.set_x_legend(x_legend)
    chart.set_y_legend(y_legend)
    chart.x_axis = x
    chart.y_axis = y

    chart << line_hollow
    chart << line
    chart << line_dot

    render :text => chart.to_s
  end
  
  def renderpie
    

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/account.html.erb
<h1>Votre compte</h1>

<h3>Mécontent?</h3>
<p><%= link_to "Supprimer mon compte", registration_path(current_user), :confirm => "Êtes vous sûr?", :method => :delete %>.</p>

app/views/welcome/index.html.erb
<h1>Bienvenue</h1>

<% if iphone_user_agent? # Show message for iPhone users -%>
<div class="message">
    <p>Using an iPhone? <a href="http://iphone.trawlr.com/">Use the optimised version</a>.</p>
</div>
<% end -%>

<div class="span-24 last">
		<p>Suivi interne de Serveurs, Instances de base de données & Agences</p>
</div>
<div class="span-24 last">
<% if user_signed_in? %>
	<table>
	<tbody>
	<% last_date = "#" %>
	<% last_datev = nil %>
	<% last_branch = -1 %>
	<% last_name = "" %>
	<% accu_html = "" %>
	<% nbope = 0 %>
	<% @ope.each do |o| %>
		<% if last_date != o["date_used"].to_date.to_pretty %>
	        <% if last_date != "#" %>
	            <% if last_branch != -1 %>
	          		<% accu_html += "<td colspan=#{nbope}><span class='small'>" %> 
	                <% accu_html += eval("link_to last_name, branch_path(last_branch)")  %>
	                <% accu_html += "</span></td>" %>
	            <% end %>
				<td><div class="calendar2">
	    			<span class="month"><%= link_to I18n.localize(last_datev, :format => "%b"), "/calendar/#{last_datev.year}/#{last_datev.month}" %></span>
	    			<span class="day"><%= link_to last_datev.day, "/calendar/#{last_datev.year}/#{last_datev.month}/#{last_datev.day}" %></span>
				</td></div></tr>
	          	<% accu_html += "<td></td>" %> 
	  			<tr><%= raw accu_html %></tr>
	        <% end %>
	        <tr>  
	    	<% last_date = o["date_used"].to_date.to_pretty %>
	        <td rowspan="2"><%= last_date %></td>
	        <% accu_html = "" %>
	  	    <% last_branch = -1 %>
	  	    <% last_name = "" %>
   			<% last_datev = o["date_used"].to_date %>
			<td><div class="calendar2">
    			<span class="month"><%= link_to I18n.localize(last_datev, :format => "%b"), "/calendar/#{last_datev.year}/#{last_datev.month}" %></span>
    			<span class="day"><%= link_to last_datev.day, "/calendar/#{last_datev.year}/#{last_datev.month}/#{last_datev.day}" %></span>
			</td></div>
          	<% accu_html += "<td></td>" %> 
	    <% end %>
	    <% if last_branch != o["branch_id"].to_i %>
	    	<% if last_branch != -1 %>
          		<% accu_html += "<td colspan=#{nbope}><span class='small'>" %> 
                <% accu_html += eval("link_to last_name, branch_path(last_branch)")  %>
                <% accu_html += "</span></td>" %>
	        <% end %>
	        <% nbope = 0 %>
	        <% last_branch = o["branch_id"].to_i %>
	        <% last_name = o["branch_name"] %>
	    <% end %>
	   	<td><%= eval("link_to image_tag('"+o["operation_name"].downcase+"-"+o["status"]+".png', :alt =>'"+o["operation_description"]+"' ), "+o["eventable_type"].downcase+"_event_path(o['target_id'].to_i,o['id'].to_i)") %></td>
   		<% last_datev = o["date_used"].to_date %>
	   	<% nbope += 1 %>
	<% end %>  
	<% if last_branch != -1 %>
    	<% accu_html += "<td colspan=#{nbope}><span class='small'>" %> 
        <% accu_html += eval("link_to last_name, branch_path(last_branch)")  %>
        <% accu_html += "</span></td>" %>
		<td><div class="calendar2">
   			<span class="month"><%= link_to I18n.localize(last_datev, :format => "%b"), "/calendar/#{last_datev.year}/#{last_datev.month}" %></span>
   			<span class="day"><%= link_to last_datev.day, "/calendar/#{last_datev.year}/#{last_datev.month}/#{last_datev.day}" %></span>
		</td></div>
       	<% accu_html += "<td></td>" %> 
	<% end %>
	</td></tr>
	<tr><%= raw accu_html %></tr>
	</tbody></table>
<% end %>
</div>	  

app/views/welcome/index.iphone.erb
<ul title="Suivi opérations" selected="true">
  <li class="panel">Interventions</li>
  <% last_branch = -1 %>
  <% last_date = "#" %>
  <% @ope.each do |o| %>
      <% if last_date !=  o["date_used"].to_date.to_pretty %>
        <% last_date = o["date_used"].to_date.to_pretty %>
        <li class="group"><%= last_date %></li>
      <% end %>
      <% if last_branch !=  o["branch_id"] %>
        <li class="panel"><%= o["branch_name"] %></li>
        <% last_branch = o["branch_id"] %>
      <% end %>
   	  <%= eval("link_to image_tag('"+o["operation_name"].downcase+"-"+o["status"]+".png', :alt =>'"+o["operation_description"]+"' ), "+o["eventable_type"].downcase+"_event_path(o['target_id'].to_i,o['id'].to_i)") %>
	<!-- >  <li class="toolbar"><%= o["operation_description"] %></li> -->
  <% end %>
  <li class="group">Menu principal</li>
  <li><%= link_to 'Agences', branches_path %></li>
  <li><%= link_to 'Serveurs', servers_path %></li>
  <li><%= link_to 'Instances', instances_path %></li>
  <li class="group">Autres actions</li>
  <li><%= link_to 'Agenda', calendar_path %></li>
  <li><%= link_to 'Entités', entities_path %></li>
</ul>  

app/views/welcome/indexmap.html.erb
<h1>Bienvenue</h1>

<% if iphone_user_agent? # Show message for iPhone users -%>
<div class="message">
    <p>Using an iPhone? <a href="http://iphone.trawlr.com/">Use the optimised version</a>.</p>
</div>
<% end -%>

<div class="span-24 last">
		<p>Suivi interne de Serveurs, Instances de base de données & Agences</p>
</div>
<div class="span-24 last">
	<% if user_signed_in? %>
		<%= raw Cartographer::Header.new.to_s %>
		<%= raw @map.to_html %>
		<div style="width:700px;height:700px;" id="map" >[Map] 
		</div>
	<% end %>
</div>
	  

app/views/welcome/sample_ajax.html.erb
<%= link_to @branch.entity.description, @branch.entity %>-
<%= link_to @branch.description, @branch %><br/>
<%= pluralize(@branch.servers.count,"serveur") %>

app/views/welcome/stat.html.erb
<div class="span-24 last">
	<% if user_signed_in? %>
		<h1>Répartition des étapes</h1>
			<div>
				<%= raw @graph3%>
			</div>
		</div>
	<% end %>
</div>	  

<div class="span-24 last">
	<% if user_signed_in? %>
		<h1>Etat des installations</h1>
		<div>
			<%= raw @graph1%>
		</div>
	<% end %>
</div>	  

<div class="span-24 last">
	<% if user_signed_in? %>
		<h1>Etat des migrations</h1>
		<div>
			<%= raw @graph2%>
		</div>
	<% end %>
</div>	  