config/routes.rb
Toudoux::Application.routes.draw do
  resources :intervenants

  resources :operations

  resources :opegroups

  get "events/index"
  get "events/install_status"
  get "events/period/:period" => "events#index"
  get "events/newcal"

  get "test_it/index"

  get "welcome/account"
  get "welcome/indexmap"
  get "welcome/stat"
  get "welcome/graph_install"
  get "welcome/graph_migrate"
  get "welcome/pie_status"
  match "welcome/sample_ajax/:id" => "welcome#sample_ajax"

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}
  
  resources :entities

  resources :environments

  resources :instances do
  	  resources :events do
 	  	resources :intervenants, :controller => "event_interv_links"
  	  end
  end

  resources :servers do
  	  resources :events do
  	  	resources :intervenants, :controller => "event_interv_links" 
	  end
  end

  resources :branches do
  	  resources :events do
  	  	resources :intervenants, :controller => "event_interv_links"
  	  end
  end

  get "welcome/index"

  devise_for :users

  root :to => "welcome#index"

end

app/models/operation.rb
class Operation < ActiveRecord::Base
  belongs_to :opegroup
  has_many :events
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_filter :authenticate_user!
  # GET /operations
  # GET /operations.xml
  def index
    @operations = Operation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @operations }
    end
  end

  # GET /operations/1
  # GET /operations/1.xml
  def show
    @operation = Operation.find(params[:id])
    @events = @operation.events
    
    @interventions = Event.find :all, 
                                :joins => :operation, 
                                :conditions => ["operations.id = ?",@operation.id],
                                :order => "coalesce(cancelled,done,planned) ASC"
    
    #.where(
    # 	"(planned between :startdate and :enddate) or "+
    #    "(done between :startdate and :enddate) or "+
    #    "(cancelled between :startdate and :enddate)",
    #	{:startdate => Date.current-21, :enddate => Date.current+15}).
  	#	order("planned ASC")

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @operation }
    end
  end

  # GET /operations/new
  # GET /operations/new.xml
  def new
    @operation = Operation.new
    @opegroups = Opegroup.find(:all)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @operation }
    end
  end

  # GET /operations/1/edit
  def edit
    @operation = Operation.find(params[:id])
    @opegroups = Opegroup.find(:all)
  end

  # POST /operations
  # POST /operations.xml
  def create
    @operation = Operation.new(params[:operation])

    respond_to do |format|
      if @operation.save
        format.html { redirect_to(@operation, :notice => 'Operation was successfully created.') }
        format.xml  { render :xml => @operation, :status => :created, :location => @operation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @operation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /operations/1
  # PUT /operations/1.xml
  def update
    @operation = Operation.find(params[:id])

    respond_to do |format|
      if @operation.update_attributes(params[:operation])
        format.html { redirect_to(@operation, :notice => 'Operation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @operation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.xml
  def destroy
    @operation = Operation.find(params[:id])
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to(operations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% @operation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br />
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="span-24">
	  <div class="span-8 field">
	    <%= f.label :spriteplan %><br />
	    <%= f.text_field :spriteplan %>
	  </div>
	  <div class="span-8 field">
	    <%= f.label :spritedone %><br />
	    <%= f.text_field :spritedone %>
	  </div>
	  <div class="span-8 last field">
	    <%= f.label :spritecancel %><br />
	    <%= f.text_field :spritecancel %>
	  </div>
  </div>	
  <div class="field">
    <%= f.label :opegroup_id %><br />
    <%= f.select :opegroup_id, @opegroups.collect {|s| [s.name, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :cal_color %><br />
    <%= f.text_field :cal_color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<h1>Listing operations</h1>

<table>
  <tr>
    <th>Nom</th>
    <th>Nom court</th>
    <th>Description & couleur</th>
    <th>Groupe d'opérations</th>
    <th></th>
    <th></th>
  </tr>

<% @operations.each do |operation| %>
  <tr>
    <td><%= link_to operation.name, operation %></td>
    <td style="background-color: <%= operation.cal_color %>"><%= operation.short_name %></td>
    <td><%= operation.description %></td>
    <td><%= operation.opegroup.description %></td>
    <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
    <td><%= link_to 'Destroy', operation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Operation', new_operation_path %>

app/views/operations/new.html.erb
<h1>New operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p style="background-color: <%= @operation.cal_color %>">
  <b>Name:</b>
  <%= @operation.name %>
  (nom court: <%= @operation.short_name %> )
  
</p>

<p>
  <b>Description:</b>
  <%= @operation.description %>
</p>

<p>
  <b>Decoration:</b>
  <% unless @operation.spriteplan.nil? %>
	<span class="ss_sprite <%= @operation.spriteplan %>">Planifié</span>&nbsp;
  <% else %> 
	Planifié : Non renseigné&nbsp;
  <% end %>
  <% unless @operation.spritedone.nil? %>
	<span class="ss_sprite <%= @operation.spritedone %>">Réalisé</span>&nbsp;
  <% else %> 
	Réalisé : Non renseigné&nbsp;
  <% end %>
  <% unless @operation.spritecancel.nil? %>
	<span class="ss_sprite <%= @operation.spritecancel %>">Annulé</span>&nbsp;
  <% else %> 
	Annulé : Non renseigné&nbsp;
  <% end %>
</p>


<p>
  <b>Groupe d'opérations:</b>
  <%= link_to @operation.opegroup.name, @operation.opegroup %>
</p>

<%= render :partial => "shared/events", :locals => { :events => @interventions } %>

<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>